=== Kevin-Cravioto/40270/xml/gramatica.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT perfil (nombre, juego, nivel, biografia, logros)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT juego (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>

<!ELEMENT biografia (#PCDATA)>

<!ELEMENT logros (logro+)>
<!ELEMENT logro (#PCDATA)>

<!ATTLIST juego plataforma (Xbox | PC | PS5) "Xbox">

=== Kevin-Cravioto/40270/xml/gramatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE perfil SYSTEM "gramatica.dtd">

<perfil>
    <nombre>KevinPro_99</nombre>
    <juego plataforma="Xbox">Need for Speed</juego>
    <nivel>Leyenda</nivel>
    
    <biografia>Entusiasta de la velocidad y los juegos de carreras. Siempre buscando mejorar el tiempo en pista.</biografia>
    
    <logros>
        <logro>Campeón de la temporada 2025</logro>
        <logro>Coleccionista de autos clásicos</logro>
        <logro>Nivel 100 alcanzado</logro>
    </logros>
</perfil>
